### ISSUE TITLE
scTransform

### ISSUE THREAD

**Issue by massonix** [bvieth/scRNA-seq-pipelines#1]
Dear Beate,

Congratulation on your last preprint, it has provided me and the whole single-cell community with very clear guidelines to improve our scRNA-seq pipelines. In this regard, I would kindly like two ask you two questions about your analysis:

- Do you plan to benchmark scran with cluster against Seurat's scTransform (https://satijalab.org/seurat/v3.0/sctransform_vignette.html)? Your findings that scran is the best performing tool for normalizations are consistent with this paper: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5549838/ . However, considering the widespread of Seurat these days, it would be very useful if their claims on scTransform are right. To my knowledge, it remains to be reported.

- Could you expand on why MAST appeared as the worst DE tool? In this review: https://www.nature.com/articles/nmeth.4612, it was the second best performing tool (see figure 5).

Thanks a lot for your time and effort!

Best regards,

Ramon

**Comment by bvieth** [comment]
Dear Ramon,

thank you for your message and I am glad to hear you found our study useful.

Concerning your questions, indeed it would be interesting to see how Seurat scTransform compares to  scran with clustering. I will try to implement it in powsimR and give it a quick run. 

So in our comparison, we in a way extended the analysis of Soneson and Robinson (2018) by considering asymmetric expression differences.  We actually found that MAST is a good DE-tool for full-length RNA-seq protocols such as Smart-seq2. This is actually in line with Soneson and Robinson since their simulations are based on a collection of three scRNA-seq experiments using full length methods (Smartseq, Smart-seq2 and SMARTer C1). But here we also considered simulation of UMI data and found that MAST had a comparable TPR, but lost FDR control, resulting in lowered pAUC values compared to limma-trend. 

Thanks again for your interest!

Kind regards,
Beate

**Comment by massonix** [comment]
This is really enlightening, thanks a lot Beate. I will use all your findings to guide my own analysis! 

Best regards,

Ramon
