### ISSUE TITLE
Question about ERCC genes in Ziegenhain dataset

### ISSUE THREAD

**Issue by xuebaliang** [bvieth/scRNA-seq-pipelines#2]
Hello, I have some trouble in finding the ERCC files of  Ziegenhain dataset in paper <Comparative
analysis of single-cell RNA sequencing methods>.  It is likely not on GSE75790 in NCBI . Therefore can you send me it? I want to know the true concentration level of those ERCC genes.  Another question is that whether you know the cell types(clusters) for these 583 cells. Thanks.

**Comment by bvieth** [comment]
Hello,

my apologies for answering so late. I turned off the github notifications since my email would have gotten flooded otherwise.

So concerning your question you can actually find the concentration tables and count matrices for the SCRBseq and Smartseq2 prepared cells in the folder simulation/ saved as rds files. There are no different cell types since they are all mouse embryonic stem cells.

Kind regards
Beate
