### ISSUE TITLE
Adapter/polyA trim of SMART-Seq2 data?

### ISSUE THREAD

**Issue by heathergeiger** [bvieth/scRNA-seq-pipelines#3]
Did you perform any adapter or polyA trimming of the SMART-Seq2 data? Only trimming I saw mentioned in the methods section of the paper was to trim the reads down to 45bp rather than for any specific sequences.

I am working on a SMART-Seq2 dataset that seems to have some frequently repeated sequences with matches to carp genome in BLAST, which I know is an indicator of adapter contamination. Also see a lot of long polyA/polyT stretches at the ends of reads. Assuming most of these will just not map, but wondering if cutadapt to trim these before alignment would be a better approach.

**Comment by bvieth** [comment]
Hello, 

my sincerest apologies for not answering this sooner, I turned off a lot of notifications from github since my email would have gotten flooded otherwise.

So, I actually used the sequencing data from the original publication (Ziegenhain et al. 2017) since it was inhouse for me. For that publication, we did not trim sequences for adapters nor tails generated using Smartseq2. The trimming to 45bp was needed to make the different sequencing runs of the library preparations comparable.

Kind regards
Beate
